# Basic `dependabot.yml` file with
# minimum configuration for two package managers

version: 2
updates:
  - package-ecosystem: github-actions
    directory: ".github/workflows"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
