name: Test
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run Hadolint
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
  functional:
    runs-on: ubuntu-latest
    name: Test upload
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          key_id: ${{ secrets.B2_KEY_ID }}
          application_key: ${{ secrets.B2_APPLICATION_KEY }}
          bucket_name: ${{ secrets.B2_BUCKET_NAME }}
          file_path: action.yml
          remote_path: backblaze-b2-github-action
